version: "3.8"
services:
  postgres:
    image: "postgres"
    container_name: go-bitly_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - go-bitly_network

  go-bitly:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    container_name: go-bitly_go-bitly
    command: ./server
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - go-bitly_network
    env_file:
      - .env.dev

volumes:
  postgres-data:

networks:
  go-bitly_network:
    driver: bridge
